export const ACTIVE_BOARD_COLS = 10;
export const ACTIVE_BOARD_ROWS = 8;

export const VISUAL_BOARD_COLS = 15;
export const VISUAL_BOARD_ROWS = 9;

export const ACTIVE_BOARD_COL_OFFSET = 2;
export const ACTIVE_BOARD_ROW_OFFSET = 0;

export const ACTIVE_BOARD_ASPECT = ACTIVE_BOARD_COLS / ACTIVE_BOARD_ROWS;
export const VISUAL_BOARD_ASPECT = VISUAL_BOARD_COLS / VISUAL_BOARD_ROWS;
